export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const USER_SIGN_OUT   = 'USER_SIGN_OUT';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const TOGGLE_PROFILE_MENU = 'TOGGLE_PROFILE_MENU'

export const LISTS_GET_REQUEST = 'LISTS_GET_REQUEST';
export const LISTS_GET_SUCCESS = 'LISTS_GET_SUCCESS';
export const LISTS_GET_FAILURE = 'LISTS_GET_FAILURE';

export const LIST_REQUEST = 'LIST_REQUEST';
export const LIST_FAILURE = 'LIST_FAILURE';
export const LIST_CREATE_SUCCESS = 'LIST_CREATE_SUCCESS';
export const LIST_UPDATE_SUCCESS = 'LIST_UPDATE_SUCCESS';
export const LIST_REMOVE_SUCCESS = 'LIST_REMOVE_SUCCESS';
export const LIST_ADD_NEW     = 'LIST_ADD_NEW';
export const LIST_REMOVE_NEW  = 'LIST_REMOVE_NEW';

export const TODO_REQUEST = 'TODO_REQUEST';
export const TODO_FAILURE = 'TODO_FAILURE';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS';
export const TODO_REMOVE_SUCCESS = 'TODO_REMOVE_SUCCESS';

export const TODO_ADD_NEW    = 'TODO_ADD_NEW';
export const TODO_REMOVE_NEW = 'TODO_REMOVE_NEW';
